# Locators of Sing in Page
UserNameLocator = //input[@id='username']
PasswordLocator = //input[@id='password']
loginButton = //button[@id='submit']

# Username and Passwords
Username = student
Password = Password123
